// The map's country geometry and the join between it and the app's guessable
// country set (`src/countries.json`).
//
// Both JSON inputs are generated by `node scripts/build-map-geometry.mjs`, which
// rewrites Natural Earth's ISO-numeric geometry ids to the alpha-2 codes used
// throughout the app — so joining here is a plain id lookup, with no mapping
// table shipped to the browser.

import { feature } from "topojson-client";
import type { GeometryCollection, Topology } from "topojson-specification";

import countriesJSON from "../countries.json";
import stragglersJSON from "./stragglers.json";
import topoJSON from "./countries-50m.topo.json";

type CountryGeometry = {
  id?: string;
  properties?: { name?: string };
};

export type CountryTopology = {
  objects: { countries: { geometries: CountryGeometry[] } };
};

/** TopoJSON country shapes, as generated by `build-map-geometry.mjs`. */
export const topology = topoJSON as unknown as CountryTopology;

/** One country's shape, drawn by the map. `id` is the alpha-2 code. */
export type CountryFeature = {
  id?: string;
  type: "Feature";
  properties: { name?: string } | null;
  geometry: unknown;
};

/**
 * The same shapes as GeoJSON, expanded once for the life of the page.
 *
 * TopoJSON is what ships — the arcs between two countries are stored once — but
 * nothing can draw it until it is expanded, and that is work with a place to
 * happen. react-simple-maps' own `<Geographies>` does it in an *effect*, so a
 * freshly mounted map draws an empty world for one commit and the countries for
 * the next: the blank frame the player sees as the map flashing on the way into
 * a screen. Expanding at module scope means the shapes exist before any map
 * does, and every map that mounts thereafter has them in its first render
 * (see `BaseMap`'s `Countries`).
 */
export const countryFeatures: CountryFeature[] = feature(
  topoJSON as unknown as Topology,
  topoJSON.objects.countries as unknown as GeometryCollection,
).features as unknown as CountryFeature[];

export type StragglerMarker = {
  code: string;
  name: string;
  coordinates: Coordinates;
};

/** [lon, lat], the order react-simple-maps' `<Marker>` expects. */
export type Coordinates = [number, number];

const countryByCode = new Map(countriesJSON.map((c) => [c.code, c]));
const codeByLowerName = new Map(
  countriesJSON.map((c) => [c.name.toLowerCase(), c.code]),
);

/** Guessable countries that Natural Earth draws as a polygon on the map. */
export const polygonCodes: ReadonlySet<string> = new Set(
  topology.objects.countries.geometries
    .map((geometry) => geometry.id)
    .filter((id): id is string => id !== undefined && countryByCode.has(id)),
);

/**
 * Guessable countries with no comfortably clickable polygon (micro-states, tiny
 * islands, and the handful Natural Earth omits). Each gets a point-marker at its
 * centroid so every country stays committable from the map.
 */
export const stragglerMarkers: StragglerMarker[] = stragglersJSON.flatMap(
  (code) => {
    const name = countryNameByCode(code);
    const coordinates = countryCoordinates(code);
    if (!name || !coordinates) return [];
    return [{ code, name, coordinates }];
  },
);

export function countryNameByCode(code: string): string | undefined {
  return countryByCode.get(code)?.name;
}

/**
 * The centroid the geo-hint maths already uses for this country, or undefined
 * if `countries.json` carries no usable one (a marker there would land at NaN,
 * i.e. nowhere).
 */
export function countryCoordinates(code: string): Coordinates | undefined {
  const country = countryByCode.get(code);
  if (!country) return undefined;
  const lon = parseFloat(country.lon);
  const lat = parseFloat(country.lat);
  if (!Number.isFinite(lon) || !Number.isFinite(lat)) return undefined;
  return [lon, lat];
}

export function countryCodeByName(name: string): string | undefined {
  return codeByLowerName.get(name.toLowerCase());
}
